//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аvailability
    {
        public int id_availability { get; set; }
        public int id_medicine { get; set; }
        public string quantity { get; set; }
        public string price { get; set; }
        public int id_pharmacy { get; set; }
    
        public virtual Medicines Medicines { get; set; }
        public virtual Pharmacies Pharmacies { get; set; }
    }
}
